### ISSUE TITLE
Rename hydra/core.UnitType to hydra/core.Unit

### ISSUE THREAD

**Issue by joshsh** [CategoricalData/hydra#123]
The `UnitType` type in Hydra Core is, unlike its siblings `IntegerType`, `MapType`, etc. not used exclusively in type definitions. The one and only instance of this type is the unit value, which is used throughout Hydra at both the term and the type level. Rename the type to `Unit`.

**Comment by wisnesky** [comment]
unit is also the empty tuple and empty record

**Comment by joshsh** [comment]
Empty tuple is different in Hydra (though yes it can be considered equivalent), and there are also other empty records of n Hydra which are distinct from unit. It’s the canonical empty record, though.

**Comment by joshsh** [comment]
This has been done for a while. Close.
