### ISSUE TITLE
Port Flows module to Java

### ISSUE THREAD

**Issue by aman-dureja** [CategoricalData/hydra#17]
https://github.com/CategoricalData/hydra/blob/main/hydra-haskell/src/main/haskell/Hydra/Monads.hs

This may have to be dealt with differently in Java than it is in Haskell

**Comment by joshsh** [comment]
Yes, there is code here (the typeclass implementations) which simply doesn't translate into Java, though all of the named functions should carry over

**Comment by joshsh** [comment]
Mostly done. Now called `Flows.hs` and `Flows.java`.

**Comment by joshsh** [comment]
Completely done.
