### ISSUE TITLE
Hydra slack requires an invite

### ISSUE THREAD

**Issue by KnowledgeGarden** [CategoricalData/hydra#2]
The link given in this repo presumes prior membership

**Comment by joshsh** [comment]
FYI, I have updated the README to indicate that an invite is required. Happy to whitelist your domain if Slack lets me!

**Comment by KnowledgeGarden** [comment]
topicquests,org

**Comment by joshsh** [comment]
Added!

**Comment by KnowledgeGarden** [comment]
I am able to land on the signin page to the hydra slack. Always was. But, none of my other slack logins work; it's clear to me that either you add a generic invite link at this repo, or I share my email address with which you can invite me in.

**Comment by joshsh** [comment]
Please try [this](https://join.slack.com/t/graphcommunity/shared_invite/zt-1a6ohrnn9-rXIBwn3L4NSC4cH0c1DN8A).
